export const reservations = [
  {
    id: 1,
    userId: 1,
    accommodationId: 1,
    guestsNum: 3,
    totalPrice: 250,
    priceByGuest: 83,
    reservationStart: "11/2/2023",
    reservationEnd: "11/2/2023",
    reservationStatus: "INVALID",
  },
  {
    id: 2,
    userId: 2,
    accommodationId: 2,
    guestsNum: 8,
    totalPrice: 550,
    priceByGuest: 83,
    reservationStart: "1/5/2023",
    reservationEnd: "23/5/2023",
    reservationStatus: "PENDING",
  },
  {
    id: 3,
    userId: 3,
    accommodationId: 3,
    guestsNum: 1,
    totalPrice: 50,
    priceByGuest: 50,
    reservationStart: "1/8/2023",
    reservationEnd: "3/8/2023",
    reservationStatus: "ACCEPTED",
  },
  {
    id: 1,
    userId: 1,
    accommodationId: 1,
    guestsNum: 3,
    totalPrice: 250,
    priceByGuest: 83,
    reservationStart: "11/2/2023",
    reservationEnd: "11/2/2023",
    reservationStatus: "INVALID",
  },
  {
    id: 1,
    userId: 1,
    accommodationId: 1,
    guestsNum: 3,
    totalPrice: 250,
    priceByGuest: 83,
    reservationStart: "11/2/2023",
    reservationEnd: "11/2/2023",
    reservationStatus: "INVALID",
  },
  {
    id: 1,
    userId: 1,
    accommodationId: 1,
    guestsNum: 3,
    totalPrice: 250,
    priceByGuest: 83,
    reservationStart: "11/2/2023",
    reservationEnd: "11/2/2023",
    reservationStatus: "INVALID",
  },
  {
    id: 1,
    userId: 1,
    accommodationId: 1,
    guestsNum: 3,
    totalPrice: 250,
    priceByGuest: 83,
    reservationStart: "11/2/2023",
    reservationEnd: "11/2/2023",
    reservationStatus: "INVALID",
  },
  {
    id: 1,
    userId: 1,
    accommodationId: 1,
    guestsNum: 3,
    totalPrice: 250,
    priceByGuest: 83,
    reservationStart: "11/2/2023",
    reservationEnd: "11/2/2023",
    reservationStatus: "INVALID",
  },
];

export const profile = {
  username: "blagoje",
  password: "ddsffgdf",
  email: "blagojevic@gmal.com",
  name: "Njegos",
  surname: "Blagojevic",
  address: "Zmaj Ognjena Vuka 14",
  role: "HOST",
};

export const accommodations = [
  {
    id: 1,
    userId: 1,
    name: "Vikendica",
    description: "Prelepa vikendica na palicu",
    minGuestNum: 1,
    maxGuestNum: 5,
    autoApproceReservation: true,
    tags: ["fsdgd", "Gdfg", "gfdg", "fsg"],
    images: [],
    location: {
      id: 1,
      name: "fdgfd",
      fullAddress: "12fdsfdg sg ",
      lon: 1,
      lat: 12,
    },
    availability: {
      id: 1,
      accommodation: null,
      allRangePeriods: [],
      allPatternPeriods: [],
      price: null,
    },
  },
  {
    id: 1,
    userId: 1,
    name: "Vikendica",
    description: "Prelepa vikendica na palicu",
    minGuestNum: 1,
    maxGuestNum: 5,
    autoApproceReservation: true,
    tags: ["fsdgd", "Gdfg", "gfdg", "fsg"],
    images: [],
    location: {
      id: 1,
      name: "fdgfd",
      fullAddress: "12fdsfdg sg ",
      lon: 1,
      lat: 12,
    },
    availability: {
      id: 1,
      accommodation: null,
      allRangePeriods: [],
      allPatternPeriods: [],
      price: null,
    },
  },
  {
    id: 1,
    userId: 1,
    name: "Vikendica",
    description: "Prelepa vikendica na palicu",
    minGuestNum: 1,
    maxGuestNum: 5,
    autoApproceReservation: true,
    tags: ["fsdgd", "Gdfg", "gfdg", "fsg"],
    images: [],
    location: {
      id: 1,
      name: "fdgfd",
      fullAddress: "12fdsfdg sg ",
      lon: 1,
      lat: 12,
    },
    availability: {
      id: 1,
      accommodation: null,
      allRangePeriods: [],
      allPatternPeriods: [],
      price: null,
    },
  },
  {
    id: 1,
    userId: 1,
    name: "Vikendica",
    description: "Prelepa vikendica na palicu",
    minGuestNum: 1,
    maxGuestNum: 5,
    autoApproceReservation: true,
    tags: ["fsdgd", "Gdfg", "gfdg", "fsg"],
    images: [],
    location: {
      id: 1,
      name: "fdgfd",
      fullAddress: "12fdsfdg sg ",
      lon: 1,
      lat: 12,
    },
    availability: {
      id: 1,
      accommodation: null,
      allRangePeriods: [],
      allPatternPeriods: [],
      price: null,
    },
  },
  {
    id: 1,
    userId: 1,
    name: "Vikendica",
    description: "Prelepa vikendica na palicu",
    minGuestNum: 1,
    maxGuestNum: 5,
    autoApproceReservation: true,
    tags: ["fsdgd", "Gdfg", "gfdg", "fsg"],
    images: [],
    location: {
      id: 1,
      name: "fdgfd",
      fullAddress: "12fdsfdg sg ",
      lon: 1,
      lat: 12,
    },
    availability: {
      id: 1,
      accommodation: null,
      allRangePeriods: [],
      allPatternPeriods: [],
      price: null,
    },
  },
  {
    id: 1,
    userId: 1,
    name: "Vikendica",
    description: "Prelepa vikendica na palicu",
    minGuestNum: 1,
    maxGuestNum: 5,
    autoApproceReservation: true,
    tags: ["fsdgd", "Gdfg", "gfdg", "fsg"],
    images: [],
    location: {
      id: 1,
      name: "fdgfd",
      fullAddress: "12fdsfdg sg ",
      lon: 1,
      lat: 12,
    },
    availability: {
      id: 1,
      accommodation: null,
      allRangePeriods: [],
      allPatternPeriods: [],
      price: null,
    },
  },
];
